### PR TITLE
README correction/added kununu.com referrer

### PR DESCRIPTION
**Pull request by sanjabonic**
The links to the two contributors were in the wrong place.

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks @sanjabonic ! Can you sign our CLA please: https://github.com/snowplow/snowplow/wiki/CLA

**Comment by sanjabonic** [comment]
Hey @alexanderdean - I already did last Friday, you should see my name there.

**Comment by alexanderdean** [comment]
Confirmed - thanks so much!

**Comment by alexanderdean** [comment]
Commit was no longer retrievable but manually added kununu into [data-jun-2017](/snowplow/referer-parser/tree/data-jun-2017), closing

**Pull request closed without merging**
