### PR TITLE
Fix for ITU as it was incorrectly indented

### PR DESCRIPTION
**Pull request by danm**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: **Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.**

Once you've signed, please reply here (e.g. `I signed it!`) and we'll verify. Thanks.

**Comment by calbatron** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @calbatron has signed the Individual Contributor License Agreement. Thanks so much.

**Comment by danm** [comment]
@alexanderdean has this gone stale? any chance for a merge :)

**Comment by alexanderdean** [comment]
Cherry-picked into [data-jun-2017](/snowplow/referer-parser/tree/data-jun-2017), closing

**Pull request closed without merging**
