### PR TITLE
Add t.umblr domain to Tumblr

### PR DESCRIPTION
**Pull request by stankud**
Added another domain to Tumblr.

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks! Can you sign the CLA please: https://github.com/snowplow/snowplow/wiki/CLA

**Comment by stankud** [comment]
@alexanderdean I signed the corporate CLA since I'm doing this in a professional capacity. Did you want me to sign the personal CLA as well?

**Comment by alexanderdean** [comment]
Hi @stankud - no that's fine, I can see your signature, thanks so much!

**Comment by stankud** [comment]
Not sure why travis is sad, node tests passed locally.

**Comment by alexanderdean** [comment]
The Node.js files are auto-generated from the file `resources/referers.yml`, so I manually added `t.umblr.com` into that file in the branch [data-jun-2017](/snowplow/referer-parser/tree/data-jun-2017), closing

**Pull request closed without merging**
