### PR TITLE
fixing alignment for domain forums.whirlpool.net.au in referers.yml

### PR DESCRIPTION
**Pull request by saj1th**

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by saj1th** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @saj1th has signed the Individual Contributor License Agreement. Thanks so much

**Comment by BenFradet** [comment]
Thanks! merged 👍

**Comment by thomas91310** [comment]
@BenFradet 
I just downloaded https://s3-eu-west-1.amazonaws.com/snowplow-hosted-assets/third-party/referer-parser/referers-latest.yml and there is a misalignment for "Whirlpool".
I see that https://github.com/snowplow/referer-parser/pull/171 got merged. When can we expect https://s3-eu-west-1.amazonaws.com/snowplow-hosted-assets/third-party/referer-parser/referers-latest.yml to reflect the changes? End of the month?

**Comment by alexanderdean** [comment]
Thanks for flagging @thomas91310. Hopefully we will get to a regular update process on the referers database soon.

**Pull request merged**
