### PR TITLE
Updated referers.yml

### PR DESCRIPTION
**Pull request by tsileo**
Updated the bundled referers.yml in the golang version, and fixed example in README.

### CODE REVIEW

**Comment by alexanderdean** [comment]
Hey @tsileo - sorry just saw this. You have admin perms on this repo right - feel free to merge this and  tag...

**Comment by tsileo** [comment]
I updated referers.ym and fixed #99, tests are passing.

I don't have (anymore?) admin right, can you please merge it ?

Thanks!

**Comment by alexanderdean** [comment]
I've re-invited you to the team @tsileo !

**Comment by tsileo** [comment]
I must have missed the first invitation. Thanks.

**Pull request merged**
