### PR TITLE
Fix malformed URLs in the README

### LINKED ISSUE #118: README typo
"http:/www.psychicbazaar.com/shop" seems to be invalid in the example code

### PR DESCRIPTION
**Pull request by tiborb**
- fixed #118 "http:/www.psychicbazaar.com/shop" -> "http://www.psychicbazaar.com/shop"
- $referer->getTerm() does not exist, use $referer->getSearchTerm() instead

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks @tiborb ! Can you sign the CLA please:

https://github.com/snowplow/snowplow/wiki/CLA

**Comment by tiborb** [comment]
done

**Comment by alexanderdean** [comment]
Confirmed - thanks so much!

**Comment by tiborb** [comment]
Hi @alexanderdean, are there more changes necessary?

**Comment by BenFradet** [comment]
Thanks, merging :+1:

**Pull request merged**
