### PR TITLE
Add Turkish popular traffic provider platforms

### PR DESCRIPTION
**Pull request by cagataygurturk**
I am founder of a Turkish content provider [itusozluk.com](https://www.itusozluk.com/) and we always see these added sites on our logs. I thought that it would be interesting add them.

### CODE REVIEW

**Comment by alexanderdean** [comment]
Awesome! Many thanks Çağatay, can you sign the Snowplow CLA please - https://github.com/snowplow/snowplow/wiki/CLA

**Comment by cagataygurturk** [comment]
I did it :)

**Comment by alexanderdean** [comment]
Confirmed! Thanks, we will get this scheduled

**Comment by cagataygurturk** [comment]
Please see this: https://github.com/snowplow/referer-parser/pull/91

**Pull request closed without merging**
